name: Deploy

on:
  push:
    branches: [nodejs]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Setup .env
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            echo "${{ secrets.ENV_PRODUCTION }}" > /opt/astro-boilerplate/.env

      - name: Deploy Astro
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            export GHCR_TOKEN=${{ secrets.GHCR_TOKEN }}
            echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
            cd /opt/astro-boilerplate
            docker compose pull
            docker compose up -d
            docker image prune -f
